---
- name: provisioning play
  hosts: localhost
  connection: local

  tasks:
    - name: download the requirements
      shell: |
        ansible-galaxy install --roles-path /tmp/ansible/roles -r "{{ playbook }}-requirements.yml"

    - name: "start {{ playbook }}"
      include_tasks: "{{ playbook }}.yml"
