---
- name: provisioning play
  hosts: localhost
  connection: local
  become_user: raemone
  become: yes

  tasks:
    - name: download the requirements
      shell: |
        ansible-galaxy install --roles-path /var/tmp/ansible/roles -r "{{ playbook }}-requirements.yml"

    - name: "start {{ playbook }}"
      include_tasks: "{{ playbook }}.yml"
